import type { Metadata } from "next";
import "./globals.css";
import { PrimeReactProvider } from 'primereact/api';
import Navbar from "../components/Navbar/Navbar";
import { Suspense } from "react";
import Loading from "../components/Loading/Loading";
import SidePanel from "../components/Sidebar/SidePanel";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PrimeReactProvider>
        <body className="h-screen overflow-hidden bg-white">
          <div className="fixed w-full z-50" >
            <Navbar />
          </div>
          <div className="flex h-full">
            <SidePanel />
            <div className="flex-grow overflow-y-auto pl-64 ml-3 mt-5 w-full">
              <Suspense fallback={<Loading />}>
                {children}
              </Suspense>
            </div>
          </div>
        </body>
      </PrimeReactProvider>
    </html>
  );
}